services:
    mariadb:
        container_name: web-mariadb-3
        hostname: mariadb
        image: mariadb:10.5
        restart: always
        environment:
            MARIADB_ROOT_PASSWORD: password
            MARIADB_DATABASE: webdb
            MARIADB_USER: webdb
            MARIADB_PASSWORD: password
        ports:
            - "0.0.0.0:5033:3306"

    web:
        container_name: web-app-calculator
        hostname: app
        build: .
        ports:
            - "0.0.0.0:5002:5002"